export const ADMIN_DEVICES_REQUEST = 'ADMIN_DEVICES_REQUEST';
export const ADMIN_DEVICES_SUCCESS = 'ADMIN_DEVICES_SUCCESS';
export const ADMIN_DEVICES_FAIL = 'ADMIN_DEVICES_FAIL';

export const ALL_DEVICES_REQUEST = 'ALL_DEVICES_REQUEST';
export const ALL_DEVICES_SUCCESS = 'ALL_DEVICES_SUCCESS';
export const ALL_DEVICES_FAIL = 'ALL_DEVICES_FAIL';

export const NEW_DEVICE_REQUEST = 'NEW_DEVICE_REQUEST';
export const NEW_DEVICE_SUCCESS = 'NEW_DEVICE_SUCCESS';
export const NEW_DEVICE_RESET = 'NEW_DEVICE_RESET';
export const NEW_DEVICE_FAIL = 'NEW_DEVICE_FAIL';

export const DELETE_DEVICE_REQUEST = 'DELETE_DEVICE_REQUEST';
export const DELETE_DEVICE_SUCCESS = 'DELETE_DEVICE_SUCCESS';
export const DELETE_DEVICE_RESET = 'DELETE_DEVICE_RESET';
export const DELETE_DEVICE_FAIL = 'DELETE_DEVICE_FAIL';

export const UPDATE_DEVICE_REQUEST = 'UPDATE_DEVICE_REQUEST';
export const UPDATE_DEVICE_SUCCESS = 'UPDATE_DEVICE_SUCCESS';
export const UPDATE_DEVICE_RESET = 'UPDATE_DEVICE_RESET';
export const UPDATE_DEVICE_FAIL = 'UPDATE_DEVICE_FAIL';

export const DEVICE_DETAILS_REQUEST = 'DEVICE_DETAILS_REQUEST';
export const DEVICE_DETAILS_SUCCESS = 'DEVICE_DETAILS_SUCCESS';
export const DEVICE_DETAILS_FAIL = 'DEVICE_DETAILS_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
